defaults:
  - dm
  - _self_

item_type: object

mesh_type: "default"



# o3b dataset fetch -d dm_object
# o3b dataset index -d dm_object
# o3b dataset viz   -d dm_object

# o3b dataset fetch -d dm_object -p slurm
# o3b dataset index -d dm_object -p slurm
# o3b dataset viz   -d dm_object -p slurm
