defaults:
  - dm
  - _self_

item_type: object_pair

#mesh_type: "mc16_vuni4_r256_fdinov2s"
#mesh_type: "mc16_vuni100_r256_fdiff3f"


# categories:
#  - animals
  
# subsets: 
#  - test


# o3b dataset fetch -d dm
# o3b dataset index -d dm_object
# o3b dataset index -d dm_object_pair
# o3b dataset viz   -d dm_object_pair


# o3b dataset fetch -d dm -p slurm
# o3b dataset index -d dm_object -p slurm
# o3b dataset index -d dm_object_pair -p slurm
# o3b dataset viz   -d dm_object_pair -p slurm
