# o3b dataset fetch -d hc3d_frame
# o3b dataset index -d hc3d_frame
# o3b dataset viz   -d hc3d_frame

defaults:
  - hc3d
  - _self_

class_name: HouseCorr3DFrame

item_type: frame_object

# split: "train" | "test" | "all"
split: train

# filter_is_real: false → synthetic only | true → real only
filter_is_real: false

modalities:
  - rgb
  - cam_intr4x4
  - cam_tform4x4_obj
  - category

filter_count_max:
categories:
