defaults:
  - hc3d
  - _self_

item_type: frame_object # frame, object, scene, frame_object, scene_object

mesh_type: "mc16_vuni4_r256_fdinov2s"

# o3x dataset fetch -d hc3d_object  
# o3x dataset index -d hc3d_object
# o3x dataset viz -d hc3d_object


# o3x dataset fetch -d hc3d_object -p slurm  
# o3x dataset index -d hc3d_object -p slurm
# o3x dataset viz -d hc3d_object -p slurm