# Extended OpenTTGames — table tennis event dataset
#
# o3b dataset fetch -d opentt
# o3b dataset index -d opentt
# o3b dataset viz   -d opentt
#
# On a remote platform:
# o3b dataset fetch -d opentt -p slurm
# o3b dataset index -d opentt -p slurm
# o3b dataset viz   -d opentt -p slurm

# o3b dataset preprocess -d opentt
# o3b dataset preprocess -d opentt --model Qwen/Qwen2-VL-2B-Instruct --device cuda:0
# o3b dataset preprocess -d opentt --model Qwen/Qwen3.5-4B --device cuda:0
# o3b dataset preprocess -d opentt --model Qwen/Qwen3.5-2B --device cuda:0
# o3b dataset preprocess -d opentt --model Qwen/Qwen3.5-0.8B --device cuda:0
# o3b dataset preprocess -d opentt --model Qwen/Qwen3.5-0.8B --device cuda:0
# o3b dataset preprocess -d opentt --model Qwen/Qwen3-VL-2B-Instruct --device cuda:0

# o3b dataset preprocess -d opentt --annotate
# o3b dataset preprocess -d opentt --model Qwen/Qwen3-VL-2B-Instruct --device cuda:0 --override

# Qwen/Qwen3-VL-2B-Instruct
class_name: OpenTT

path_datasets_raw:        /data/lmbraid19/sommerl/datasets
path_datasets_preprocess: /data/lmbraid19/sommerl/datasets

path_raw:        ${path_datasets_raw}/OpenTT
path_preprocess: ${path_datasets_preprocess}/OpenTT_Preprocess

split: train   # train | test | all
# note: the test videos do not show the scoreboard with numbers

scene_length: 64   # number of frames per returned Scene clip
# otherwise it is oto fiew 

#filter_count_max: 10


extra:
  frame_stride: 16    # step between consecutive frames within a clip (120fps / 4 = 30 effective fps)
  clip_stride: 512 # 1024    # step between clip start frames; default = scene_length * frame_stride
